[tool.poetry]
name = "poet"
version = "0.1.0"
description = ""
authors = ["SivashaGitHub <sirajago@amazon.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
